name: CI Pipeline (Scheduled)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * *"   # هر روز 06:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f "ci_pipeline/ci_pipeline/requirements.txt" ]; then
            pip install -r ci_pipeline/ci_pipeline/requirements.txt
          elif [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 lxml pandas feedparser
          fi

      - name: Run pipeline
        env:
          BASE: ./run_out
        run: python run_pipeline.py

      - name: Upload artifact (outputs)
        uses: actions/upload-artifact@v4
        with:
          name: run_out
          path: run_out/**
          if-no-files-found: warn
